import { EmptyFileSystem } from "langium";
import { describe, expect, test } from "vitest";
import { createExpressP11Services } from "../language/express-module.js";

const services = createExpressP11Services(EmptyFileSystem).ExpressP11;

/**
 * ISO 10303-11:2004 clause 145 defines embedded_remark recursively, so remarks
 * nest. A non-nesting lexer ends the outer remark at the inner `*)` and hands the
 * remaining commented-out text to the parser as code.
 */
const errors = (body: string): number => {
  const result = (services.parser as unknown as {
    LangiumParser: { parse: (t: string) => { parserErrors: unknown[]; lexerErrors?: unknown[] } };
  }).LangiumParser.parse(`SCHEMA s;\n${body}\nEND_SCHEMA;`);
  return result.parserErrors.length + (result.lexerErrors?.length ?? 0);
};

const ENTITY = "ENTITY foo;\n  a : INTEGER;\nEND_ENTITY;";

describe("nested remarks", () => {
  test("a nested remark does not end its parent early", () => {
    expect(errors(`(* outer (* inner *) still commented *)\n${ENTITY}`)).toBe(0);
  });

  test("the shape found in generated long forms", () => {
    // modules/functional_data/mim_lf.exp comments out a whole FUNCTION that
    // itself contains a generator remark.
    expect(
      errors(`(* RBN - not express ed1
FUNCTION dependently_instantiated(s : SET OF GENERIC) : BOOLEAN;
   (* generated by longform-generator *)
LOCAL
  n : INTEGER;
END_LOCAL;
  RETURN (TRUE);
END_FUNCTION;
*)
${ENTITY}`)
    ).toBe(0);
  });

  test("remarks nest more than two deep", () => {
    expect(errors(`(* a (* b (* c *) d *) e *)\n${ENTITY}`)).toBe(0);
  });

  test("a tagged documentation remark still lexes", () => {
    expect(errors(`${ENTITY}\n(*"s.foo"\nProse with 'quotes' and a period '.'.\n*)`)).toBe(0);
  });

  // The degenerate cases must behave exactly as the previous non-nesting pattern
  // did, so that files which are malformed under nesting semantics are unaffected.
  test("an unbalanced remark still closes at the first *), as before", () => {
    expect(errors(`(* outer (* inner *)\n${ENTITY}`)).toBe(0);
  });

  test("a remark that is never closed is still an error, as before", () => {
    expect(errors(`${ENTITY}\n(* never closed`)).toBeGreaterThan(0);
  });
});

/**
 * Scaling guard rather than a wall-clock budget: absolute timings are too noisy
 * for CI, but a matcher that backtracked or rescanned would show super-linear
 * growth. Measured on synthetic input so it needs no external corpus.
 */
describe("nested remark scanning cost", () => {
  const lexer = (services.parser as unknown as { Lexer: { tokenize: (t: string) => unknown } }).Lexer;
  const remarkHeavy = (count: number) => `SCHEMA s;\n${"(* outer (* inner *) tail *)\n".repeat(count)}${ENTITY}\nEND_SCHEMA;`;
  const fastest = (text: string): number => {
    for (let i = 0; i < 3; i++) lexer.tokenize(text);
    let best = Infinity;
    for (let i = 0; i < 5; i++) {
      const started = performance.now();
      lexer.tokenize(text);
      best = Math.min(best, performance.now() - started);
    }
    return best;
  };

  test("cost grows about linearly with the number of remarks", () => {
    const single = fastest(remarkHeavy(2000));
    const double = fastest(remarkHeavy(4000));
    // Linear would be 2x; allow generous headroom for timer noise while still
    // catching quadratic behaviour, which would be about 4x.
    expect(double / single).toBeLessThan(3);
  });

  test("deep nesting is iterative, not recursive", () => {
    const deep = `SCHEMA s;\n${"(*".repeat(5000)}${"*)".repeat(5000)}\n${ENTITY}\nEND_SCHEMA;`;
    expect(() => lexer.tokenize(deep)).not.toThrow();
  });
});
