import {
  createDefaultModule,
  //@ts-ignore
  createDefaultSharedModule,
  DeepPartial,
  //@ts-ignore
  DefaultDocumentBuilder,
  DefaultSharedModuleContext,
  inject,
  LangiumServices,
  LangiumSharedServices,
  Module,
  PartialLangiumServices,
} from "langium";
import { ExpressP11GeneratedModule, ExpressP11GeneratedSharedModule } from "./generated/module";
import { ExpressP11Validator, registerValidationChecks } from "./express-p11-validator";
import { ExpressP11DocumentSymbolProvider } from "./express-p11-document-symbol-provider";

import { ExpressP11ScopeComputation } from "./express-p11-scope-computation";

import { ExpressP11ScopeProvider } from "./express-p11-scope-provider";
import { ExpressP11CodeActionProvider } from "./express-p11-code-action-provider";

import { ExpressP11CompletionProvider } from "./express-p11-completion-provider";
import { ExpressP11References } from "./express-p11-references";
import { ExpressDocumentValidator } from "./express-p11-document-validator";

import { ExpressP11DocumentBuilder } from "./express-p11-document-builder";
import { ExpressP11NameProvider } from "./express-p11-name-provider";
import { ScopingCache } from "../utils/caching";
import { ExpressP11IndexManager } from "./express-p11-index-manager";
import { ExpressP11NodeKindProvider } from "./express-p11-node-kind-provider";
import { ExpressP11TypeContainer } from "./express-p11-type-container";

/**
 * Declaration of custom services - add your own service classes here.
//  */
export type ExpressP11AddedServices = {
  validation: {
    ExpressP11Validator: ExpressP11Validator;
  };
  caching: {
    CustomCache: ScopingCache;
  };
  shared: ExpressP11SharedServices;
};

export type ExpressP11AddedSharedServices = {
  workspace: {
    DocumentBuilder: ExpressP11DocumentBuilder;
    IndexManager: ExpressP11IndexManager;
    TypeContainer: ExpressP11TypeContainer;
  };
  lsp: {
    NodeKindProvider: ExpressP11NodeKindProvider;
  };
};

export const ExpressP11SharedModule: Module<ExpressP11SharedServices, DeepPartial<ExpressP11SharedServices>> = {
  workspace: {
    DocumentBuilder: (services) => new ExpressP11DocumentBuilder(services),
    IndexManager: (services) => new ExpressP11IndexManager(services),
    TypeContainer: (services) => new ExpressP11TypeContainer(services),
  },
  lsp: {
    NodeKindProvider: () => new ExpressP11NodeKindProvider(),
  },
};
/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ExpressP11Services = LangiumServices & ExpressP11AddedServices;
export type ExpressP11SharedServices = LangiumSharedServices & ExpressP11AddedSharedServices;
/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ExpressP11Module: Module<ExpressP11Services, DeepPartial<ExpressP11Services>> = {
  validation: {
    ExpressP11Validator: (services) => new ExpressP11Validator(services),
    DocumentValidator: (services) => new ExpressDocumentValidator(services),
  },
  caching: {
    CustomCache: (services) => new ScopingCache(services),
  },
  lsp: {
    DocumentSymbolProvider: (services) => new ExpressP11DocumentSymbolProvider(services),
    CodeActionProvider: () => new ExpressP11CodeActionProvider(),
    CompletionProvider: (services) => new ExpressP11CompletionProvider(services),
  },
  references: {
    ScopeComputation: (services) => new ExpressP11ScopeComputation(services),
    References: (services) => new ExpressP11References(services),
    ScopeProvider: (services) => new ExpressP11ScopeProvider(services),
    NameProvider: () => new ExpressP11NameProvider(),
  },
};

export interface ExpressP11SharedModuleContext extends DefaultSharedModuleContext {
  module?: Module<ExpressP11Services, DeepPartial<ExpressP11Services>>;
  sharedModule?: Module<ExpressP11SharedServices, DeepPartial<ExpressP11SharedServices>>;
}

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createExpressP11Services(context: ExpressP11SharedModuleContext): {
  shared: ExpressP11SharedServices;
  ExpressP11: ExpressP11Services;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    ExpressP11GeneratedSharedModule,
    ExpressP11SharedModule,
    context.sharedModule
  );
  const ExpressP11 = inject(
    createDefaultModule({ shared }),
    ExpressP11GeneratedModule,
    ExpressP11Module,
    context.module
  );
  shared.ServiceRegistry.register(ExpressP11);
  //   registerValidationChecks(ExpressP11);
  return { shared, ExpressP11 };
}

// export function createCustomSharedModule(
//   context: DefaultSharedModuleContext
// ): Module<LangiumSharedServices, LangiumDefaultSharedServices> {
//   return {
//     ServiceRegistry: () => new DefaultServiceRegistry(),
//     lsp: {
//       Connection: () => context.connection,
//       LanguageServer: (services) => new DefaultLanguageServer(services),
//     },
//     workspace: {
//       LangiumDocuments: (services) => new DefaultLangiumDocuments(services),
//       LangiumDocumentFactory: (services) => new DefaultLangiumDocumentFactory(services),
//       DocumentBuilder: (services) => new ExpressP11DocumentBuilder(services),
//       TextDocuments: () => new TextDocuments(TextDocument),
//       IndexManager: (services) => new DefaultIndexManager(services),
//       WorkspaceManager: (services) => new DefaultWorkspaceManager(services),
//       FileSystemProvider: (services) => context.fileSystemProvider(services),
//       MutexLock: () => new MutexLock(),
//       ConfigurationProvider: (services) => new DefaultConfigurationProvider(services),
//     },
//   };
// }
