import {
  createDefaultModule,
  createDefaultSharedModule,
  DefaultSharedModuleContext,
  inject,
  LangiumServices,
  LangiumSharedServices,
  Module,
  PartialLangiumServices,
} from "langium";
import { ExpressP11GeneratedModule, ExpressP11GeneratedSharedModule } from "./generated/module";
import { ExpressP11Validator, registerValidationChecks } from "./express-p-11-validator";
import { ExpressP11DocumentSymbolProvider } from "./document-symbol-provider";
import { ExpressP11ScopeComputation } from "./scope-computation";
import { ExpressP11ScopeProvider } from "./scope-provider";
import { ExpressP11CodeActionProvider } from "./code-actions";
import { ExpressP11CompletionProvider } from "./completion-provider";
import { ExpressP11References } from "./references";
import { ExpressDocumentValidator } from "../document-validator";

/**
 * Declaration of custom services - add your own service classes here.
//  */
export type ExpressP11AddedServices = {
  validation: {
    ExpressP11Validator: ExpressP11Validator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ExpressP11Services = LangiumServices & ExpressP11AddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ExpressP11Module: Module<ExpressP11Services, PartialLangiumServices & ExpressP11AddedServices> = {
  validation: {
    ExpressP11Validator: (services) => new ExpressP11Validator(services),
    DocumentValidator: (services) => new ExpressDocumentValidator(services),
  },

  lsp: {
    DocumentSymbolProvider: (services) => new ExpressP11DocumentSymbolProvider(services),
    CodeActionProvider: () => new ExpressP11CodeActionProvider(),
    CompletionProvider: (services) => new ExpressP11CompletionProvider(services),
  },
  references: {
    ScopeComputation: (services) => new ExpressP11ScopeComputation(services),
    References: (services) => new ExpressP11References(services),
    ScopeProvider: (services) => new ExpressP11ScopeProvider(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createExpressP11Services(context: DefaultSharedModuleContext): {
  shared: LangiumSharedServices;
  ExpressP11: ExpressP11Services;
} {
  const shared = inject(createDefaultSharedModule(context), ExpressP11GeneratedSharedModule);
  const ExpressP11 = inject(createDefaultModule({ shared }), ExpressP11GeneratedModule, ExpressP11Module);
  shared.ServiceRegistry.register(ExpressP11);
  registerValidationChecks(ExpressP11);
  return { shared, ExpressP11 };
}

// export function createCustomSharedModule(
//   context: DefaultSharedModuleContext
// ): Module<LangiumSharedServices, LangiumDefaultSharedServices> {
//   return {
//     ServiceRegistry: () => new DefaultServiceRegistry(),
//     lsp: {
//       Connection: () => context.connection,
//       LanguageServer: (services) => new DefaultLanguageServer(services),
//     },
//     workspace: {
//       LangiumDocuments: (services) => new DefaultLangiumDocuments(services),
//       LangiumDocumentFactory: (services) => new DefaultLangiumDocumentFactory(services),
//       DocumentBuilder: (services) => new ExpressP11DocumentBuilder(services),
//       TextDocuments: () => new TextDocuments(TextDocument),
//       IndexManager: (services) => new DefaultIndexManager(services),
//       WorkspaceManager: (services) => new DefaultWorkspaceManager(services),
//       FileSystemProvider: (services) => context.fileSystemProvider(services),
//       MutexLock: () => new MutexLock(),
//       ConfigurationProvider: (services) => new DefaultConfigurationProvider(services),
//     },
//   };
// }
